/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaoCaoRouteImport } from './routes/bao-cao'
import { Route as KhachHangRouteImport } from './routes/khach-hang'
import { Route as KhuyenMaiRouteImport } from './routes/khuyen-mai'
import { Route as MauSizeRouteImport } from './routes/mau-size'
import { Route as SanPhamRouteImport } from './routes/san-pham'
import { Route as DonHangIndexRouteImport } from './routes/don-hang.index'
import { Route as DonHangOrderIdRouteImport } from './routes/don-hang.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaoCaoRoute = BaoCaoRouteImport.update({
  id: '/bao-cao',
  path: '/bao-cao',
  getParentRoute: () => rootRouteImport,
} as any)
const KhachHangRoute = KhachHangRouteImport.update({
  id: '/khach-hang',
  path: '/khach-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const KhuyenMaiRoute = KhuyenMaiRouteImport.update({
  id: '/khuyen-mai',
  path: '/khuyen-mai',
  getParentRoute: () => rootRouteImport,
} as any)
const MauSizeRoute = MauSizeRouteImport.update({
  id: '/mau-size',
  path: '/mau-size',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamRoute = SanPhamRouteImport.update({
  id: '/san-pham',
  path: '/san-pham',
  getParentRoute: () => rootRouteImport,
} as any)
const DonHangIndexRoute = DonHangIndexRouteImport.update({
  id: '/don-hang/',
  path: '/don-hang/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonHangOrderIdRoute = DonHangOrderIdRouteImport.update({
  id: '/don-hang/$orderId',
  path: '/don-hang/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bao-cao': typeof BaoCaoRoute
  '/khach-hang': typeof KhachHangRoute
  '/khuyen-mai': typeof KhuyenMaiRoute
  '/mau-size': typeof MauSizeRoute
  '/san-pham': typeof SanPhamRoute
  '/don-hang/$orderId': typeof DonHangOrderIdRoute
  '/don-hang/': typeof DonHangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bao-cao': typeof BaoCaoRoute
  '/khach-hang': typeof KhachHangRoute
  '/khuyen-mai': typeof KhuyenMaiRoute
  '/mau-size': typeof MauSizeRoute
  '/san-pham': typeof SanPhamRoute
  '/don-hang/$orderId': typeof DonHangOrderIdRoute
  '/don-hang': typeof DonHangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bao-cao': typeof BaoCaoRoute
  '/khach-hang': typeof KhachHangRoute
  '/khuyen-mai': typeof KhuyenMaiRoute
  '/mau-size': typeof MauSizeRoute
  '/san-pham': typeof SanPhamRoute
  '/don-hang/$orderId': typeof DonHangOrderIdRoute
  '/don-hang/': typeof DonHangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bao-cao'
    | '/khach-hang'
    | '/khuyen-mai'
    | '/mau-size'
    | '/san-pham'
    | '/don-hang/$orderId'
    | '/don-hang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bao-cao'
    | '/khach-hang'
    | '/khuyen-mai'
    | '/mau-size'
    | '/san-pham'
    | '/don-hang/$orderId'
    | '/don-hang'
  id:
    | '__root__'
    | '/'
    | '/bao-cao'
    | '/khach-hang'
    | '/khuyen-mai'
    | '/mau-size'
    | '/san-pham'
    | '/don-hang/$orderId'
    | '/don-hang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaoCaoRoute: typeof BaoCaoRoute
  KhachHangRoute: typeof KhachHangRoute
  KhuyenMaiRoute: typeof KhuyenMaiRoute
  MauSizeRoute: typeof MauSizeRoute
  SanPhamRoute: typeof SanPhamRoute
  DonHangOrderIdRoute: typeof DonHangOrderIdRoute
  DonHangIndexRoute: typeof DonHangIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bao-cao': {
      id: '/bao-cao'
      path: '/bao-cao'
      fullPath: '/bao-cao'
      preLoaderRoute: typeof BaoCaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khach-hang': {
      id: '/khach-hang'
      path: '/khach-hang'
      fullPath: '/khach-hang'
      preLoaderRoute: typeof KhachHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khuyen-mai': {
      id: '/khuyen-mai'
      path: '/khuyen-mai'
      fullPath: '/khuyen-mai'
      preLoaderRoute: typeof KhuyenMaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mau-size': {
      id: '/mau-size'
      path: '/mau-size'
      fullPath: '/mau-size'
      preLoaderRoute: typeof MauSizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham': {
      id: '/san-pham'
      path: '/san-pham'
      fullPath: '/san-pham'
      preLoaderRoute: typeof SanPhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/don-hang/': {
      id: '/don-hang/'
      path: '/don-hang'
      fullPath: '/don-hang/'
      preLoaderRoute: typeof DonHangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/don-hang/$orderId': {
      id: '/don-hang/$orderId'
      path: '/don-hang/$orderId'
      fullPath: '/don-hang/$orderId'
      preLoaderRoute: typeof DonHangOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaoCaoRoute: BaoCaoRoute,
  KhachHangRoute: KhachHangRoute,
  KhuyenMaiRoute: KhuyenMaiRoute,
  MauSizeRoute: MauSizeRoute,
  SanPhamRoute: SanPhamRoute,
  DonHangOrderIdRoute: DonHangOrderIdRoute,
  DonHangIndexRoute: DonHangIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
