/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MauSizeRouteImport } from './routes/mau-size'
import { Route as SanPhamRouteImport } from './routes/san-pham'
import { Route as DonHangIndexRouteImport } from './routes/don-hang.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MauSizeRoute = MauSizeRouteImport.update({
  id: '/mau-size',
  path: '/mau-size',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamRoute = SanPhamRouteImport.update({
  id: '/san-pham',
  path: '/san-pham',
  getParentRoute: () => rootRouteImport,
} as any)
const DonHangIndexRoute = DonHangIndexRouteImport.update({
  id: '/don-hang/',
  path: '/don-hang/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mau-size': typeof MauSizeRoute
  '/san-pham': typeof SanPhamRoute
  '/don-hang/': typeof DonHangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mau-size': typeof MauSizeRoute
  '/san-pham': typeof SanPhamRoute
  '/don-hang': typeof DonHangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mau-size': typeof MauSizeRoute
  '/san-pham': typeof SanPhamRoute
  '/don-hang/': typeof DonHangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mau-size' | '/san-pham' | '/don-hang/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mau-size' | '/san-pham' | '/don-hang'
  id: '__root__' | '/' | '/mau-size' | '/san-pham' | '/don-hang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MauSizeRoute: typeof MauSizeRoute
  SanPhamRoute: typeof SanPhamRoute
  DonHangIndexRoute: typeof DonHangIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mau-size': {
      id: '/mau-size'
      path: '/mau-size'
      fullPath: '/mau-size'
      preLoaderRoute: typeof MauSizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham': {
      id: '/san-pham'
      path: '/san-pham'
      fullPath: '/san-pham'
      preLoaderRoute: typeof SanPhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/don-hang/': {
      id: '/don-hang/'
      path: '/don-hang'
      fullPath: '/don-hang/'
      preLoaderRoute: typeof DonHangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MauSizeRoute: MauSizeRoute,
  SanPhamRoute: SanPhamRoute,
  DonHangIndexRoute: DonHangIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
